export const ESPECIAIS_DATA = {
  subsections: [
    {
      id: "INST", label: "Institucionais",
      items: [
        { id:"INST-1", label:"Logo Oficial" },
        { id:"INST-2", label:"Bola Oficial" },
        { id:"INST-3", label:"Mascote" },
        { id:"INST-4", label:"Troféu FIFA" },
      ],
    },
    {
      id: "ESCU", label: "Escudos Metalizados",
      items: [
        "México","África do Sul","Coreia do Sul","Rep. Tcheca","Canadá","Catar","Suíça","Bósnia-Herz.",
        "Brasil","Marrocos","Haiti","Escócia","Estados Unidos","Paraguai","Austrália","Turquia",
        "Alemanha","Curaçao","Costa do Marfim","Equador","Países Baixos","Japão","Tunísia","Suécia",
        "Bélgica","Egito","Irã","Nova Zelândia","Espanha","Cabo Verde","Arábia Saudita","Uruguai",
        "França","Senegal","Noruega","Iraque","Argentina","Argélia","Áustria","Jordânia",
        "Portugal","Uzbequistão","Colômbia","RD Congo","Inglaterra","Croácia","Gana","Panamá",
      ].map((name,i)=>({ id:`ESCU-${i+1}`, label:`Escudo: ${name}` })),
    },
    {
      id: "STAD", label: "Estádios-Sede Metalizados",
      items: [
        "Estadio Azteca (CDMX)","Estadio Akron (Guadalajara)","Estadio BBVA (Monterrey)",
        "AT&T Stadium (Dallas)","SoFi Stadium (Los Angeles)","Levi's Stadium (San Francisco)",
        "MetLife Stadium (Nova York)","Gillette Stadium (Boston)","Lincoln Financial Field (Filadelfia)",
        "Mercedes-Benz Stadium (Atlanta)","Hard Rock Stadium (Miami)","Arrowhead Stadium (Kansas City)",
        "NRG Stadium (Houston)","Lumen Field (Seattle)","BMO Field (Toronto)","BC Place (Vancouver)",
      ].map((name,i)=>({ id:`STAD-${i+1}`, label:`Estádio: ${name}` })),
    },
  ],
};

export const TEAMS = [
  { id:"MEX", name:"México",          flag:"🇲🇽", group:"A" },
  { id:"ZAF", name:"África do Sul",   flag:"🇿🇦", group:"A" },
  { id:"KOR", name:"Coreia do Sul",   flag:"🇰🇷", group:"A" },
  { id:"CZE", name:"Rep. Tcheca",     flag:"🇨🇿", group:"A" },
  { id:"CAN", name:"Canadá",          flag:"🇨🇦", group:"B" },
  { id:"QAT", name:"Catar",           flag:"🇶🇦", group:"B" },
  { id:"SUI", name:"Suíça",           flag:"🇨🇭", group:"B" },
  { id:"BIH", name:"Bósnia-Herz.",    flag:"🇧🇦", group:"B" },
  { id:"BRA", name:"Brasil",          flag:"🇧🇷", group:"C" },
  { id:"MAR", name:"Marrocos",        flag:"🇲🇦", group:"C" },
  { id:"HAI", name:"Haiti",           flag:"🇭🇹", group:"C" },
  { id:"SCO", name:"Escócia",         flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿", group:"C" },
  { id:"USA", name:"Estados Unidos",  flag:"🇺🇸", group:"D" },
  { id:"PAR", name:"Paraguai",        flag:"🇵🇾", group:"D" },
  { id:"AUS", name:"Austrália",       flag:"🇦🇺", group:"D" },
  { id:"TUR", name:"Turquia",         flag:"🇹🇷", group:"D" },
  { id:"GER", name:"Alemanha",        flag:"🇩🇪", group:"E" },
  { id:"CUW", name:"Curaçao",         flag:"🇨🇼", group:"E" },
  { id:"CIV", name:"Costa do Marfim", flag:"🇨🇮", group:"E" },
  { id:"ECU", name:"Equador",         flag:"🇪🇨", group:"E" },
  { id:"NED", name:"Países Baixos",   flag:"🇳🇱", group:"F" },
  { id:"JPN", name:"Japão",           flag:"🇯🇵", group:"F" },
  { id:"TUN", name:"Tunísia",         flag:"🇹🇳", group:"F" },
  { id:"SWE", name:"Suécia",          flag:"🇸🇪", group:"F" },
  { id:"BEL", name:"Bélgica",         flag:"🇧🇪", group:"G" },
  { id:"EGY", name:"Egito",           flag:"🇪🇬", group:"G" },
  { id:"IRN", name:"Irã",             flag:"🇮🇷", group:"G" },
  { id:"NZL", name:"Nova Zelândia",   flag:"🇳🇿", group:"G" },
  { id:"ESP", name:"Espanha",         flag:"🇪🇸", group:"H" },
  { id:"CPV", name:"Cabo Verde",      flag:"🇨🇻", group:"H" },
  { id:"KSA", name:"Arábia Saudita",  flag:"🇸🇦", group:"H" },
  { id:"URU", name:"Uruguai",         flag:"🇺🇾", group:"H" },
  { id:"FRA", name:"França",          flag:"🇫🇷", group:"I" },
  { id:"SEN", name:"Senegal",         flag:"🇸🇳", group:"I" },
  { id:"NOR", name:"Noruega",         flag:"🇳🇴", group:"I" },
  { id:"IRQ", name:"Iraque",          flag:"🇮🇶", group:"I" },
  { id:"ARG", name:"Argentina",       flag:"🇦🇷", group:"J" },
  { id:"ALG", name:"Argélia",         flag:"🇩🇿", group:"J" },
  { id:"AUT", name:"Áustria",         flag:"🇦🇹", group:"J" },
  { id:"JOR", name:"Jordânia",        flag:"🇯🇴", group:"J" },
  { id:"POR", name:"Portugal",        flag:"🇵🇹", group:"K" },
  { id:"UZB", name:"Uzbequistão",     flag:"🇺🇿", group:"K" },
  { id:"COL", name:"Colômbia",        flag:"🇨🇴", group:"K" },
  { id:"COD", name:"RD Congo",        flag:"🇨🇩", group:"K" },
  { id:"ENG", name:"Inglaterra",      flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", group:"L" },
  { id:"CRO", name:"Croácia",         flag:"🇭🇷", group:"L" },
  { id:"GHA", name:"Gana",            flag:"🇬🇭", group:"L" },
  { id:"PAN", name:"Panamá",          flag:"🇵🇦", group:"L" },
];

export const NUMS = Array.from({length:20},(_,i)=>i+1);

export const PRESETS = [
  { label:"🌸 Rosa",  c1:"#FF6B9D", c2:"#AA00FF", c3:"#FF3CAC" },
  { label:"🌊 Azul",  c1:"#0077FF", c2:"#00C6FF", c3:"#004AAD" },
  { label:"🌿 Verde", c1:"#00B894", c2:"#00CEC9", c3:"#55EFC4" },
  { label:"🔥 Fogo",  c1:"#FF4500", c2:"#FF8C00", c3:"#FFD700" },
  { label:"🌙 Noite", c1:"#6C63FF", c2:"#3F3D56", c3:"#FF6584" },
  { label:"⚽ Copa",  c1:"#009C3B", c2:"#FFDF00", c3:"#003893" },
];
