export const ESPECIAIS_DATA = {
  subsections: [
    {
      id: "FWC",
      label: "⚽ FWC — FIFA World Cup",
      emoji: "🏆",
      items: [
        { id:"FWC-0",  label:"FWC 0 — Figurinha Panini" },
        { id:"FWC-1",  label:"FWC 1 — Emblema Oficial" },
        { id:"FWC-2",  label:"FWC 2 — (Página inicial)" },
        { id:"FWC-3",  label:"FWC 3 — Mascotes Oficiais" },
        { id:"FWC-4",  label:"FWC 4 — Slogan Oficial" },
        { id:"FWC-5",  label:"FWC 5 — Bola Oficial (TRIONDA)" },
        { id:"FWC-6",  label:"FWC 6 — Emblema CAN (Canadá)" },
        { id:"FWC-7",  label:"FWC 7 — Emblema MEX (México)" },
        { id:"FWC-8",  label:"FWC 8 — Emblema USA (EUA)" },
        { id:"FWC-9",  label:"FWC 9 — História: Final 1934 (Itália)" },
        { id:"FWC-10", label:"FWC 10 — História: Final 1950 (Uruguai)" },
        { id:"FWC-11", label:"FWC 11 — História: Final 1954 (Alemanha)" },
        { id:"FWC-12", label:"FWC 12 — História: Final 1962 (Brasil)" },
        { id:"FWC-13", label:"FWC 13 — História: Final 1966 (Inglaterra)" },
        { id:"FWC-14", label:"FWC 14 — História: Final 1986 (Argentina)" },
        { id:"FWC-15", label:"FWC 15 — História: Final 1994 (Brasil)" },
        { id:"FWC-16", label:"FWC 16 — História: Final 2002 (Brasil)" },
        { id:"FWC-17", label:"FWC 17 — História: Final 2006 (Itália)" },
      ],
    },
    {
      id: "CC",
      label: "🥤 CC — Coca-Cola",
      emoji: "🥤",
      items: [
        { id:"CC-1",  label:"CC 1 — Lamine Yamal (Espanha)" },
        { id:"CC-2",  label:"CC 2 — Joshua Kimmich (Alemanha)" },
        { id:"CC-3",  label:"CC 3 — Harry Kane (Inglaterra)" },
        { id:"CC-4",  label:"CC 4 — Santiago Giménez (México)" },
        { id:"CC-5",  label:"CC 5 — Joško Gvardiol (Croácia)" },
        { id:"CC-6",  label:"CC 6 — Federico Valverde (Uruguai)" },
        { id:"CC-7",  label:"CC 7 — Jefferson Lerma (Colômbia)" },
        { id:"CC-8",  label:"CC 8 — Enner Valencia (Equador)" },
        { id:"CC-9",  label:"CC 9 — Gabriel Magalhães (Brasil)" },
        { id:"CC-10", label:"CC 10 — Virgil van Dijk (Países Baixos)" },
        { id:"CC-11", label:"CC 11 — Alphonso Davies (Canadá)" },
        { id:"CC-12", label:"CC 12 — Emiliano Martínez (Argentina)" },
        { id:"CC-13", label:"CC 13 — Raúl Jiménez (México)" },
        { id:"CC-14", label:"CC 14 — Lautaro Martínez (Argentina)" },
      ],
    },
  ],
};

export const TEAMS = [
  { id:"MEX", name:"México",          flag:"🇲🇽", group:"A" },
  { id:"ZAF", name:"África do Sul",   flag:"🇿🇦", group:"A" },
  { id:"KOR", name:"Coreia do Sul",   flag:"🇰🇷", group:"A" },
  { id:"CZE", name:"Rep. Tcheca",     flag:"🇨🇿", group:"A" },
  { id:"CAN", name:"Canadá",          flag:"🇨🇦", group:"B" },
  { id:"QAT", name:"Catar",           flag:"🇶🇦", group:"B" },
  { id:"SUI", name:"Suíça",           flag:"🇨🇭", group:"B" },
  { id:"BIH", name:"Bósnia-Herz.",    flag:"🇧🇦", group:"B" },
  { id:"BRA", name:"Brasil",          flag:"🇧🇷", group:"C" },
  { id:"MAR", name:"Marrocos",        flag:"🇲🇦", group:"C" },
  { id:"HAI", name:"Haiti",           flag:"🇭🇹", group:"C" },
  { id:"SCO", name:"Escócia",         flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿", group:"C" },
  { id:"USA", name:"Estados Unidos",  flag:"🇺🇸", group:"D" },
  { id:"PAR", name:"Paraguai",        flag:"🇵🇾", group:"D" },
  { id:"AUS", name:"Austrália",       flag:"🇦🇺", group:"D" },
  { id:"TUR", name:"Turquia",         flag:"🇹🇷", group:"D" },
  { id:"GER", name:"Alemanha",        flag:"🇩🇪", group:"E" },
  { id:"CUW", name:"Curaçao",         flag:"🇨🇼", group:"E" },
  { id:"CIV", name:"Costa do Marfim", flag:"🇨🇮", group:"E" },
  { id:"ECU", name:"Equador",         flag:"🇪🇨", group:"E" },
  { id:"NED", name:"Países Baixos",   flag:"🇳🇱", group:"F" },
  { id:"JPN", name:"Japão",           flag:"🇯🇵", group:"F" },
  { id:"TUN", name:"Tunísia",         flag:"🇹🇳", group:"F" },
  { id:"SWE", name:"Suécia",          flag:"🇸🇪", group:"F" },
  { id:"BEL", name:"Bélgica",         flag:"🇧🇪", group:"G" },
  { id:"EGY", name:"Egito",           flag:"🇪🇬", group:"G" },
  { id:"IRN", name:"Irã",             flag:"🇮🇷", group:"G" },
  { id:"NZL", name:"Nova Zelândia",   flag:"🇳🇿", group:"G" },
  { id:"ESP", name:"Espanha",         flag:"🇪🇸", group:"H" },
  { id:"CPV", name:"Cabo Verde",      flag:"🇨🇻", group:"H" },
  { id:"KSA", name:"Arábia Saudita",  flag:"🇸🇦", group:"H" },
  { id:"URU", name:"Uruguai",         flag:"🇺🇾", group:"H" },
  { id:"FRA", name:"França",          flag:"🇫🇷", group:"I" },
  { id:"SEN", name:"Senegal",         flag:"🇸🇳", group:"I" },
  { id:"NOR", name:"Noruega",         flag:"🇳🇴", group:"I" },
  { id:"IRQ", name:"Iraque",          flag:"🇮🇶", group:"I" },
  { id:"ARG", name:"Argentina",       flag:"🇦🇷", group:"J" },
  { id:"ALG", name:"Argélia",         flag:"🇩🇿", group:"J" },
  { id:"AUT", name:"Áustria",         flag:"🇦🇹", group:"J" },
  { id:"JOR", name:"Jordânia",        flag:"🇯🇴", group:"J" },
  { id:"POR", name:"Portugal",        flag:"🇵🇹", group:"K" },
  { id:"UZB", name:"Uzbequistão",     flag:"🇺🇿", group:"K" },
  { id:"COL", name:"Colômbia",        flag:"🇨🇴", group:"K" },
  { id:"COD", name:"RD Congo",        flag:"🇨🇩", group:"K" },
  { id:"ENG", name:"Inglaterra",      flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", group:"L" },
  { id:"CRO", name:"Croácia",         flag:"🇭🇷", group:"L" },
  { id:"GHA", name:"Gana",            flag:"🇬🇭", group:"L" },
  { id:"PAN", name:"Panamá",          flag:"🇵🇦", group:"L" },
];

export const NUMS = Array.from({length:20},(_,i)=>i+1);

export const PRESETS = [
  { label:"🌸 Rosa",  c1:"#FF6B9D", c2:"#AA00FF", c3:"#FF3CAC" },
  { label:"🌊 Azul",  c1:"#0077FF", c2:"#00C6FF", c3:"#004AAD" },
  { label:"🌿 Verde", c1:"#00B894", c2:"#00CEC9", c3:"#55EFC4" },
  { label:"🔥 Fogo",  c1:"#FF4500", c2:"#FF8C00", c3:"#FFD700" },
  { label:"🌙 Noite", c1:"#6C63FF", c2:"#3F3D56", c3:"#FF6584" },
  { label:"⚽ Copa",  c1:"#009C3B", c2:"#FFDF00", c3:"#003893" },
];
